### ISSUE TITLE
Show all dataset values on focus?

### ISSUE THREAD

**Issue by anthonyjoanes** [Siyfion/angular-typeahead#89]
Is it possible to show all the values in the dataset when the input gets focus? I have a use case where I need to make it obvious that there are values behind the input box so that users can make a selection from the list as well as input their own if the one they need doesn't exist.

**Comment by hmil** [comment]
This issue is specific to [typeahead.js](https://github.com/twitter/typeahead.js), not angular-typeahead. 
You will need to set `options.minLength = 0` and make sure your data `source` yields some suggestions for an empty query string (which bloodhound doesn't seem to do by default but if you use a custom `source` method it should be rather straightforward).

**Comment by anthonyjoanes** [comment]
Hmm yes I looked into that, not sure about the custom source method, this wrapped asks for the ttAdapter. I've found one for ui-bootstrap which seems to work quite well so I think I will have to go down that route.

**Comment by hmil** [comment]
`angular-typeahead` forwards the `options` and `datasets` parameters so the workaround like [this one](http://stackoverflow.com/questions/19797370/twitter-typeahead-js-show-all-options-when-click-focus) should work without any problem.
